services:
  nextjs:
    build: .
    container_name: market-nextjs
    restart: always
    ports:
      - '3000:3000'
    environment:
      MONGODB_URI: mongodb://host.docker.internal:27017/market
      NODE_ENV: development
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
